### ISSUE TITLE
Ignoring auth requests can prevent stations from associating indefinitely

### ISSUE THREAD

**Issue by mweinelt** [blogic/usteer#3]
I see lots of ignored auth requests on multiple APs:

```
usteer: Ignoring auth request from 5c:cf:7f:f9:4d:3d, node (local/remote): hostapd.client0_vlan110/192.168.42.104#hostapd.client1_vlan110, signal=-49/-77, n_assoc=15/4
```

The device `5c:cf:7f:f9:4d:3d` is an ESP8266 in a power socket, that is located roughly 5m from the local AP. For some reason it ignores the auth request in favor of another AP located over 40m away, through three walls outside the house in the garden.

The power plug over several hours does not try to connect to another AP except the one close to it and will therefore be denied access to the WiFi network indefinitely.

No special config was applied.

```
config usteer
	option syslog '1'
	option debug_level '2'
	option network 'vlan42'
```

**Comment by mweinelt** [comment]
One option to work around this would be the ability to enable usteer only on certain VIFs, if that info is even available at that time, so I can exclude the iot/things VIF from this kind of scrutiny.

**Comment by blogic** [comment]
This is a known issue and we are working on a fix.

**Comment by mweinelt** [comment]
Likely fixed in https://git.openwrt.org/?p=project/usteer.git;a=commit;h=d7a7f147fa067e7f61b52120a3faf70cc37c836c.
